version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: structural-db
    restart: always
    environment:
      MYSQL_DATABASE: space_truss_db_v4
      MYSQL_USER: space_truss_db_v4_user
      MYSQL_PASSWORD: 9348
      MYSQL_ROOT_PASSWORD: root
      MYSQL_INITDB_SKIP_TZINFO: 1
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      MYSQL_INNODB_BUFFER_POOL_SIZE: 128M
    ports:
      - "3311:3306"
    volumes:
      - db_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
  

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: structural-backend
    command: >
      bash -c "
      while ! nc -z db 3306; do
        echo 'Waiting for MySQL...';
        sleep 2;
      done;
      python manage.py migrate &&
      gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 2 --threads 2
      "
    volumes:
      - ./backend:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: space_truss_db_v4
      DB_USER: space_truss_db_v4_user
      DB_PASSWORD: 9348

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
      args:
      - VITE_API_BASE_URL=https://api.spacetruss.rezteche.com
    container_name: structural-frontend
    ports:
      - "5173:80"
    depends_on:
      backend:
        condition: service_healthy
  
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

volumes:
  db_data:
