version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: structural-db
    restart: always
    environment:
      MYSQL_DATABASE: space_truss_db_v4
      MYSQL_USER: space_truss_db_v4_user
      MYSQL_PASSWORD: 9348
      MYSQL_ROOT_PASSWORD: root
      MYSQL_INITDB_SKIP_TZINFO: 1
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      MYSQL_INNODB_BUFFER_POOL_SIZE: 128M
    ports:
      - "3312:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: structural-backend
    volumes:
      - ./backend:/app
    ports:
      - "8002:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: space_truss_db_v4
      DB_USER: space_truss_db_v4_user
      DB_PASSWORD: 9348
      DJANGO_DEBUG: "true"
      ALLOWED_HOSTS: "localhost,127.0.0.1,backend"
      FRONTEND_ORIGINS: "http://localhost:5174"

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.frontend
  #   container_name: structural-frontend
  #   ports:
  #     - "5174:80"
  #   depends_on:
  #     - backend


  frontend:
  build:
    context: ./frontend
    dockerfile: Dockerfile.frontend
    args:
      VITE_API_URL: https://api.spacetruss.rezteche.com
  ports:
    - "5174:80"
  depends_on:
    - backend


volumes:
  db_data: