# Generated by Django 5.1.7 on 2025-03-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startNode', models.CharField(max_length=50)),
                ('endNode', models.CharField(max_length=50)),
                ('length', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_coordinate', models.CharField(max_length=50, unique=True)),
                ('x_restrained', models.BooleanField(default=False)),
                ('y_restrained', models.BooleanField(default=False)),
                ('z_restrained', models.BooleanField(default=False)),
            ],
        ),
    ]
