# Generated by Django 5.1.7 on 2025-03-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_truss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startNode', models.CharField(max_length=50)),
                ('endNode', models.CharField(max_length=50)),
                ('length', models.FloatField()),
            ],
        ),
    ]
