# Generated by Django 5.1.7 on 2025-03-18 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_truss', '0001_initial'),
    ]

    operations = [
    ]
