# Generated by Django 5.1.7 on 2025-03-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_truss', '0002_auto_20250318_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_coordinate', models.CharField(max_length=50, unique=True)),
                ('Fx', models.FloatField(default=0.0)),
                ('Fy', models.FloatField(default=0.0)),
                ('Fz', models.FloatField(default=0.0)),
            ],
        ),
    ]
