# Generated by Django 5.1.7 on 2025-03-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_truss', '0002_elements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_coordinate', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('Pinned', 'Pinned'), ('Fixed', 'Fixed'), ('Roller', 'Roller')], max_length=10)),
                ('x_restrained', models.BooleanField(default=False)),
                ('y_restrained', models.BooleanField(default=False)),
                ('z_restrained', models.BooleanField(default=False)),
            ],
        ),
    ]
