# Generated by Django 5.1.7 on 2025-03-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_truss', '0003_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='elements',
            name='area',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='elements',
            name='youngs_modulus',
            field=models.FloatField(default=1.0),
        ),
    ]
