# Generated by Django 5.1.7 on 2025-04-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_truss', '0004_elements_area_elements_youngs_modulus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssembledGlobalStiffnessMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
